#_target_: src.wm.SimpleWorldModel
_target_: wm_v1.SimpleWorldModel

# Model architecture, training config, etc.
# TODO
layers: [256,128]
obs_dim: 39
action_dim: 4
lr: 0.001
state_coef: 1000.0
reward_coef: 10.0
term_coef: 1.0
batch_size: 128
epochs: 2
num_envs: ${..policy.cfg.num_envs}
horizon: 500
cuda: ${..policy.cfg.cuda}
run_name: ???